server:
  port: 8086

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password:

  datasource:
    url: jdbc:postgresql://localhost:5433/studytrack
    username: admin
    password:
  jpa:
    generate-ddl: true